language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2
    - otp_release: 19.2
      elixir: 1.4.2
sudo: false
notifications:
  email: false
script:
  - mix test
